#!/bin/bash
# Generate diefficiency statistics

print_usage () {
    echo "Usage: comunica-bencher dief <time> experimentpath1 [experimentpath2 [...]]"
    echo "  time       Caclulate dief t based on the intermediate time results of the given queries."
    exit 1
}

dief () {
    for experiment in $@; do
        # Check if the experiment contains the correct query output
        if [ ! -f $experiment/output/queries.csv ]; then
            echo "No output/queries.csv file could be found in the experiment '$experiment'."
            exit 1
        fi
        if ! head -n 1 $experiment/output/queries.csv | grep -q timestamps ; then
            echo "No timestamps found in output/queries.csv for experiment '$experiment'."
            exit 1
        fi
        args[((i++))]=$experiment/output/queries.csv
    done

    echo "template;name;id;dief"
    awk -F ';' '
    FNR > 1 {
      {
          time[$1,$2] = (time[$1,$2] > 0 && time[$1,$2] < $4 ? time[$1,$2] : $4);
      }
      {
          n=split($5,timestamps," ");
          prev = 0;
          dief[FILENAME,$1,$2] = 0;
          # calculate integral of graph generated by timestamps
          for (i = 1; i <= n && timestamps[i] <= time[$1,$2]; i++) {
              dief[FILENAME,$1,$2] += (timestamps[i]-prev) * (i-1);
              prev = timestamps[i];
          }
          dief[FILENAME,$1,$2] += (time[$1,$2]-prev) * n;
          
          name = FILENAME;
          gsub(/\/output\/queries.csv/, "", name);
          printf name ";" $1 ";" $2 ";" dief[FILENAME,$1,$2] "\n"
      }
    }' ${args[@]}
}

# Validate input args
if [[ $# -lt 1 ]] ; then
    echo "Error: Missing dief action"
    print_usage
fi

# Execute action
action=$1
remainingargs=${@:2}
case "$action" in
time)
    dief $remainingargs
    ;;
*)
    echo "Invalid dief action '$action'"
    print_usage
    ;;
esac